apiVersion: projectcalico.org/v3
kind: GlobalReport
metadata:
  name: daily-cis-benchmark
spec:
  reportType: cis-benchmark
  schedule: 0 0 * * *
  endpoints:
    namespaces:
      names:
        - hipstershop
  cis:
    highThreshold: 100
    medThreshold: 50
    includeUnscoredTests: true
    numFailedTests: 5
    resultsFilters:
      - benchmarkSelection: { kubernetesVersion: "1.25" }
        exclude: ["1.1.4", "1.2.5"]